Feature/contestant selector
jjm3x3/AmazingRaceFantasy pull request #35
Opened 2024-01-27 05:28 UTC by jjm3x3

Here is the main code necessary to create a contestant selector. More contestants to be added next.

2024-01-29 02:36 UTC, CAnthonySiever approved these changes
Looks good to me 👍

2024-01-29 03:41 UTC, internette requested changes
Testing?

2024-01-29 04:07 UTC, jjm3x3 commented
> Testing?

What about it? What testing should happen here?

2024-01-29 06:04 UTC, jjm3x3 commented on app/scoring/page.tsx
> -            <h1 className="text-2xl text-center">Current Scoring for {currentSelectedContestant}</h1>
I should remove `currentSelectedContestant` from the code since this is no longer used after this.

2024-01-30 04:35 UTC, internette approved these changes

2024-02-04 03:40 UTC, jjm3x3 reviewed
What is my comment 👀 
<img width="181" alt="image" src="https://github.com/jjm3x3/AmazingRaceFantasy/assets/5040219/3e8a7ad6-ecf9-4278-b8b3-bc56017275f8">

2024-02-04 03:44 UTC, jjm3x3 commented on jest.config.mjs
> +/** @type {import('jest').Config} */
According to @internette it is not necessary!

2024-02-04 04:14 UTC, merged